# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tx-Nj8cQLxbNTzAW57WoTJjEl4Upr9Yq
"""

import numpy as np

aux=np.array([[8,0,0],[7.5,0,-3],[7,0,-6],[5.5,0,-8],[4,0,-9],[2,0,-9.8],[0,0,-10],[-2,0,-9.8],[-4,0,-9],[-5.5,0,-8],[-7,0,-6],[-7.5,0,-3],[-8,0,0],[-7.5,0,3],[-7,0,6],[-5.5,0,8],[-4,0,9],[-2,0,9.8],[0,0,10],[2,0,9.8],[4,0,9],[5.5,0,8],[7,0,6],[7.5,0,3],[8,0,0]])

aux2=aux.copy()
escalax=200
escalay=221.4285
for part in range(0,aux[:,0].size):
  aux2[part,0]=(aux2[part,0]*escalax)/8
  aux2[part,2]=(aux2[part,2]*escalay)/10

for x in aux2:
  print(str(x[0])+' '+str(x[1])+' '+str(x[2])+',')